/* File generated by ToTargetConfigFile.xsl */

#define XKCP_has_Sponge_Keccak
#define XKCP_has_Xoofff
#define XKCP_has_KeccakP1600
#define XKCP_has_Xoodoo
#define XKCP_has_Xoodootimes4
#define XKCP_has_Xoodootimes8
